name             'nessus'
maintainer       'dann s washko'
maintainer_email 'dwashko@gannett.com'
license          'All rights reserved'
description      'Installs/Configures nessus'
long_description 'Installs/Configures nessus'
version          '0.1.0'
